/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Item } from "./components/todoItem/todoItem";
import { Item as Item1 } from "./components/todoItem/todoItem";
export namespace Components {
    interface FirstComp {
        "name": string;
    }
    interface ItemList {
        "delay": number;
    }
    interface TodoComplete {
        "todoItems": Item[];
    }
    interface TodoItem {
        "description": string;
        "done": boolean;
        "uuid": number;
    }
    interface TodoSection {
    }
    interface XButton {
        "enable": boolean;
    }
    interface XNavItem {
        "class": string;
    }
    interface XNavbar {
    }
}
export interface TodoItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTodoItemElement;
}
export interface TodoSectionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTodoSectionElement;
}
declare global {
    interface HTMLFirstCompElement extends Components.FirstComp, HTMLStencilElement {
    }
    var HTMLFirstCompElement: {
        prototype: HTMLFirstCompElement;
        new (): HTMLFirstCompElement;
    };
    interface HTMLItemListElement extends Components.ItemList, HTMLStencilElement {
    }
    var HTMLItemListElement: {
        prototype: HTMLItemListElement;
        new (): HTMLItemListElement;
    };
    interface HTMLTodoCompleteElement extends Components.TodoComplete, HTMLStencilElement {
    }
    var HTMLTodoCompleteElement: {
        prototype: HTMLTodoCompleteElement;
        new (): HTMLTodoCompleteElement;
    };
    interface HTMLTodoItemElement extends Components.TodoItem, HTMLStencilElement {
    }
    var HTMLTodoItemElement: {
        prototype: HTMLTodoItemElement;
        new (): HTMLTodoItemElement;
    };
    interface HTMLTodoSectionElement extends Components.TodoSection, HTMLStencilElement {
    }
    var HTMLTodoSectionElement: {
        prototype: HTMLTodoSectionElement;
        new (): HTMLTodoSectionElement;
    };
    interface HTMLXButtonElement extends Components.XButton, HTMLStencilElement {
    }
    var HTMLXButtonElement: {
        prototype: HTMLXButtonElement;
        new (): HTMLXButtonElement;
    };
    interface HTMLXNavItemElement extends Components.XNavItem, HTMLStencilElement {
    }
    var HTMLXNavItemElement: {
        prototype: HTMLXNavItemElement;
        new (): HTMLXNavItemElement;
    };
    interface HTMLXNavbarElement extends Components.XNavbar, HTMLStencilElement {
    }
    var HTMLXNavbarElement: {
        prototype: HTMLXNavbarElement;
        new (): HTMLXNavbarElement;
    };
    interface HTMLElementTagNameMap {
        "first-comp": HTMLFirstCompElement;
        "item-list": HTMLItemListElement;
        "todo-complete": HTMLTodoCompleteElement;
        "todo-item": HTMLTodoItemElement;
        "todo-section": HTMLTodoSectionElement;
        "x-button": HTMLXButtonElement;
        "x-nav-item": HTMLXNavItemElement;
        "x-navbar": HTMLXNavbarElement;
    }
}
declare namespace LocalJSX {
    interface FirstComp {
        "name"?: string;
    }
    interface ItemList {
        "delay"?: number;
    }
    interface TodoComplete {
        "todoItems"?: Item[];
    }
    interface TodoItem {
        "description"?: string;
        "done"?: boolean;
        "onShouldDelete"?: (event: TodoItemCustomEvent<number>) => void;
        "onUpdatedDescription"?: (event: TodoItemCustomEvent<Item>) => void;
        "uuid": number;
    }
    interface TodoSection {
        "onClearListEvent"?: (event: TodoSectionCustomEvent<any>) => void;
    }
    interface XButton {
        "enable"?: boolean;
    }
    interface XNavItem {
        "class"?: string;
    }
    interface XNavbar {
    }
    interface IntrinsicElements {
        "first-comp": FirstComp;
        "item-list": ItemList;
        "todo-complete": TodoComplete;
        "todo-item": TodoItem;
        "todo-section": TodoSection;
        "x-button": XButton;
        "x-nav-item": XNavItem;
        "x-navbar": XNavbar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "first-comp": LocalJSX.FirstComp & JSXBase.HTMLAttributes<HTMLFirstCompElement>;
            "item-list": LocalJSX.ItemList & JSXBase.HTMLAttributes<HTMLItemListElement>;
            "todo-complete": LocalJSX.TodoComplete & JSXBase.HTMLAttributes<HTMLTodoCompleteElement>;
            "todo-item": LocalJSX.TodoItem & JSXBase.HTMLAttributes<HTMLTodoItemElement>;
            "todo-section": LocalJSX.TodoSection & JSXBase.HTMLAttributes<HTMLTodoSectionElement>;
            "x-button": LocalJSX.XButton & JSXBase.HTMLAttributes<HTMLXButtonElement>;
            "x-nav-item": LocalJSX.XNavItem & JSXBase.HTMLAttributes<HTMLXNavItemElement>;
            "x-navbar": LocalJSX.XNavbar & JSXBase.HTMLAttributes<HTMLXNavbarElement>;
        }
    }
}
